### ISSUE TITLE
Flink Historyserver for Async Job Status

### ISSUE THREAD

**Issue by ranchodeluxe** [pangeo-forge/pangeo-forge-runner#122]
### Problem
We shouldn't have to run  `kubectl logs -f pod/<job-manager-pod> | grep 'Job BeamApp-flink-.*RUNNING to.*'` to know if a job succeeded for failed. We want to poll against something async

### Goal
Figure out how to set up and configure the [HistoryServer](https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/advanced/historyserver/)

**Comment by cisaacstern** [comment]
Good call! And related to https://github.com/pangeo-forge/pangeo-forge-runner/issues/20 where we discuss the possibility of adding a generic `pangeo-forge-runner get-logs` command that can dispatch to runner-specific (Flink, dataflow, etc.) logic for log fetching. This is also linked somewhere in that thread, but surfacing that here's a prototype of a Dataflow-specific implementation:

> https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/150/files#diff-6c7aa5c43028a369df9006f054e85f0550bf33bbf1a13b6fdccfc8a61317b67b

(@ranchodeluxe for your context, the `pangeo-forge-orchestrator` repo that contains that file is our now-defunct attempt at running a Pangeo Forge web service, which I'm now in the process of winding down.)
