### ISSUE TITLE
Flink kubernetes operator 1.5.0 not installable in tests

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-runner#149]
As seen in, e.g.:

https://github.com/pangeo-forge/pangeo-forge-runner/actions/runs/6948526467/job/18904685879

Looks like downloads.apache.org has dropped 1.5.0:

https://downloads.apache.org/flink/

@ranchodeluxe should we upgrade, or install from some other source?

**Comment by ranchodeluxe** [comment]
closing as doneso
