### ISSUE TITLE
Can I pass additional arguments to dataflow?

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/pangeo-forge-runner#72]
I am curious if it is possible to pass [Pipeline Options](https://cloud.google.com/dataflow/docs/reference/pipeline-options) to pangeo-forge-runner directly?

Specifically I want to limit the number of max workers with `max_num_workers`

**Comment by cisaacstern** [comment]
@jbusecke this is already implemented in Pangeo Forge Runner, here:

https://github.com/pangeo-forge/pangeo-forge-runner/blob/3b71752c3654b3fbab39ad242ba7901b166902ac/pangeo_forge_runner/bakery/dataflow.py#L93-L102

In general, the approach we are using is that the options we want to pass to Dataflow should be implemented as attributes of the DataflowBakery. In this case, that is already the case. If the option you wanted to pass was not already implemented, we would make a PR to add it.

**Comment by jbusecke** [comment]
Cool. Given that the cost of the job I started today turned out to be lower than my estimate, this is not that important to me at the moment, but let me link that in the leap data repo.

**Comment by cisaacstern** [comment]
Closing this because it seems like you have what you need here.
