### ISSUE TITLE
Is it possible to give a maximum runtime per job?

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/pangeo-forge-runner#91]
I have found several instances where jobs on dataflow get 'stuck', meaning they run for much longer than expected. 
So far this seems to be an intermittent problem, but when I am submitting hundreds of jobs, cancelling them manually becomes tedious. 
Is there a way to give a time after which a job is force killed at the point of submission to dataflow? Presumably the user would want to manage this on a per job basis. For instance my [CMIP6 recipes](https://github.com/leap-stc/cmip6-leap-feedstock/pull/9) will rarely take longer than a few minutes, but e.g. @cisaacstern s [climsim recipe](https://github.com/leap-stc/data-management/pull/46) often takes a few days.

**Comment by cisaacstern** [comment]
Looks like there isn't a Dataflow feature for this, see https://stackoverflow.com/a/51410414. The responder there is Google's Dataflow product manager, so I take the response to be pretty authoritative, albeit a few years old. The suggested workaround probably wouldn't be desirable using the GitHub Action, as it would require the Action's runner process to stay blocked from closing until the Dataflow job timed out. But perhaps the general approach of a supervisor ("zombie killer" 🧟 ) process is transferable. Admittedly the idea of an additional operational layer is less appealing than a simple beam pipeline option, but in this case it doesn't seem like there's an alternative. A lightweight implementation could be a Github Workflow running a "zombie hunting" chron job? 🤔

**Comment by yuvipanda** [comment]
BTW, I cancel all running jobs on dataflow with the following command:

```
❯ gcloud dataflow jobs list --status=active --format=json | jq -r ".[].id" | xargs -L1 gcloud dataflow jobs cancel --region=us-central1
```

**Comment by cisaacstern** [comment]
That's a helpful command, @yuvipanda!

Is it correct to understand that a custom list of job id's could be passed as well (instead of just _all_ jobs) by doing something like:

```
gcloud dataflow jobs cancel --region=us-central1 $SPACE_DELIMITED_JOBID_LIST 
```

?

**Comment by yuvipanda** [comment]
@cisaacstern yes, you can filter as you wish. If we were to stick to bash the easiest would be to filter in the `jq` step - pretty powerful. But if this was to be systematized, easiest is to just read the output of that JSON command into python, do whatever you need, and then kill them.

**Comment by jbusecke** [comment]
Implemented a zombie killer gh workflow [here](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/6042326775/job/16397189386). Works like a charm.

**Comment by jbusecke** [comment]
A bit off-topic but I wonder if there is a way to more gracefully end the job if there are no ids to cance ([example](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/6046156027/job/16407269843))?

**Comment by jbusecke** [comment]
I separated #46 out, and will close this now.
